---
# Debian/Ubuntu specific installation
#

- name: Update work dir in init script
  lineinfile:
    dest={{ pk_agent_init_debian }}
    regexp="^WORKDIR"
    line="WORKDIR={{ pk_agent_work_dir_name }}"

- name: Install init.d script
  command: cp {{ pk_agent_init_debian }} {{ pk_agent_init_script }}
  notify:
    - restart passware kit agent
